name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build
        run: |
          npx --yes yarn@1.22.22 install --frozen-lockfile
          npm run build
          npm test
